### PR TITLE
MIDIClientRef singleton (macOS)

### PR DESCRIPTION
**Pull request by tschiemer**
Addresses  https://github.com/thestk/rtmidi/issues/155#issuecomment-626181015

Not thoroughly tested yet but so far no problems in my multithreaded development project with regular instantiation and deletion of RtMidi-Objects..

### CODE REVIEW

**Comment by Noir-** [comment]
Would you mind merging this? This is a breaking issue and the whole open source world relies upon this library :)

**Comment by garyscavone** [comment]
No time to test … hopefully it doesn’t create a problem.

On Apr 21, 2021, at 2:59 PM, threa4ctor ***@***.******@***.***>> wrote:



Would you mind merging this? This is a breaking issue and the whole open source world relies upon this library :)

**Comment by garyscavone** [comment]
I don't see the need for the singleton function declarations to be in RtMidi.h ... I just moved them to RtMidi.cpp and it seems to work. Please let me know ASAP if this is a problem, as I will make the change shortly for the new release.

**Comment by tschiemer** [comment]
No, it is indeed not needed but was primarily ment to allow direct access to the system object, if so desired (or possibly needed, can't tell)

Please note the relevant readme passage which should be removed aswell.

Just *looking* at the code in `RtMidi.cpp` I would think you can also completely remove the declarations along with the implementations as I don't see them being used in the first place; the singleton is accessed directly in the respective MidiIn/OutCore methods.

If it works for you I would think it's safe to remove

**Comment by garyscavone** [comment]
Thanks! Fixed in latest two PRs.

**Pull request merged**
