### PR TITLE
No allocations on sendMessage

### PR DESCRIPTION
**Pull request by radarsat1**
Add a second sendMessage prototype that takes a normal C array instead of std::vector.
From discussion in #118.

### CODE REVIEW

**Comment by garyscavone** [comment]
I'm just looking at this quickly. Should there be some documentation updates, since all the previous code examples and doxygen tutorial focused on the use of a vector?

**Comment by radarsat1** [comment]
I don't think the examples need to change, the std::vector interface is still there. Of course it needs testing with stk, etc. Hopefully I'll find some time tomorrow.

**Comment by garyscavone** [comment]
Thanks for the work on this! I'm going to go ahead and merge it. However, I don't quite understand the title. One way or the other, the user will have to allocate some memory to hold the MIDI bytes. And since the sendMessage() function took a reference, it wasn't performing any data allocation itself. So, I guess the concern here is that the std::vector constructor allocates too much memory? Aren't there ways to force the std::vector to minimize it's memory footprint (such as allocating it with a fixed size)?

**Comment by sagamusix** [comment]
@garyscavone The initial motivation for writing this new overload is that my code doesn't use `std::vector` for MIDI message storage. So in the end, I had to allocate a temporary std::vector for every MIDI message to be sent. While a vector is perfectly suitable for storing MIDI messages, people may be using entirely different containers, and this pull request makes it possible.

**Comment by sagamusix** [comment]
A perfect example for this is found in the C API wrapper for RtMidi by the way, which until now had to create a `std::vector` for passing the MIDI data on. Now that this pull request is merged, the C wrapper could be optimized to no longer allocate that vector.

**Comment by radarsat1** [comment]
Thanks @garyscavone.  Just to answer your question, it's really a micro-optimisation but I think @sagamusix's point is not about the amount of memory or frequency of allocation, but (1) the ability to point to data on the stack instead of on the heap, and (2) the ability to directly provide sendMessage a pointer to memory in other container types without having to "convert" (i.e. copy) data to an std::vector.

**Pull request merged**
