### PR TITLE
Nice README with travis badge

### PR DESCRIPTION
**Pull request by MartinDelille**
Preview available here: https://github.com/MartinDelille/rtmidi/tree/readme

### CODE REVIEW

**Comment by radarsat1** [comment]
This patch breaks `make dist`

**Comment by MartinDelille** [comment]
I fix that. Is it ok?

**Comment by radarsat1** [comment]
Please squash, then I'll merge it.

**Comment by DouglasHeriot** [comment]
Nice.
Note you can turn on allowing squashing commits in Github project settings, so the pull request system can do it for you: https://github.com/blog/2141-squash-your-commits

**Comment by MartinDelille** [comment]
Squashed!

**Comment by radarsat1** [comment]
@DouglasHeriot sounds nice.  I have "Allow squash merging" turned on in the settings, but the merge button doesn't seem to have the option.  I'll try to figure that out.  In any case I generally prefer merging via the command line.

**Pull request merged**
